included:

excluded:
  - Pods
  - Cartography
  - build
  - fastlane

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - trailing_newline

line_length: 150

opt_in_rules:
- number_separator:
    minimum_length: 5

cyclomatic_complexity:
  warning: 10
  error: 12
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
