included:

excluded:
  - Pods
  - Cartography
  - build
  - fastlane

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - trailing_whitespace
  - trailing_newline

line_length: 150

number_separator:
  minimum_length: 5

cyclomatic_complexity:
  warning: 5
  error: 6
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
